In [184]:
import pandas as pd
import matplotlib.pyplot as plt
import mlxtend as mlx
import numpy as np
from mlxtend.frequent_patterns import fpgrowth, association_rules

In [185]:
df = pd.read_csv('Q_1.csv')
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

In [186]:
df_C = df[df['InvoiceNo'].str.startswith('C')]
df_c = df[df['InvoiceNo'].str.startswith('c')]

In [187]:
count_C = df_C['InvoiceNo'].nunique()
count_c = df_c['InvoiceNo'].nunique()

In [188]:
total_count = count_c+count_C
print("Total number of unique InvoiceNo that starts with c is =",total_count)

Total number of unique InvoiceNo that starts with c is = 3836


In [189]:
unique = df_C.InvoiceNo.nunique()
unique

3836

In [190]:
df = df[~df['InvoiceNo'].str.startswith('C')]
df = df[~df['InvoiceNo'].str.startswith('c')]
print("The dataframe with no InvoiceNo starting with c is")
print()
print(df.head())

The dataframe with no InvoiceNo starting with c is

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  
4  12/1/2010 8:26       3.39     17850.0  United Kingdom  


In [191]:
unique_items = df['Description'].unique()
unique_items_length = len(unique_items)

In [192]:
unique_invoice = df['InvoiceNo'].unique()
unique_invoice_length = len(unique_invoice)
len(df['StockCode'].unique())

4059

In [193]:
data_matrix = np.zeros(shape = (unique_invoice_length,unique_items_length))
data_matrix.shape

(22064, 4208)

In [194]:
unique_products = df['StockCode'].unique()

unique_invoices = df['InvoiceNo'].unique()


matrix = pd.DataFrame(0, index=unique_invoices, columns=unique_products)

for invoice_no, group in df.groupby('InvoiceNo'):
    for product in group['StockCode']:
        matrix.at[invoice_no, product] = 1

data_matrix = np.asarray(matrix)
print("The matrix is")
print(data_matrix)

The matrix is
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [195]:
print("The dataframe of matrix is")
new_df = pd.DataFrame(matrix)
print(new_df)

The dataframe of matrix is
        85123A  71053  84406B  84029G  84029E  22752  21730  22633  22632  \
536365       1      1       1       1       1      1      1      0      0   
536366       0      0       0       0       0      0      0      1      1   
536367       0      0       0       0       0      0      0      0      0   
536368       0      0       0       0       0      0      0      0      0   
536369       0      0       0       0       0      0      0      0      0   
...        ...    ...     ...     ...     ...    ...    ...    ...    ...   
581583       0      0       0       0       0      0      0      0      0   
581584       0      0       0       0       0      0      0      0      0   
581585       0      0       0       0       0      0      0      0      0   
581586       0      0       0       0       0      0      0      0      0   
581587       0      0       0       0       0      0      0      0      0   

        84879  ...  23560  23576  23562  23561  

In [196]:
frequent_itemsets = fpgrowth(matrix, min_support=0.01, use_colnames=True)
print("The frequent itemsets in new dataframe are")
print(frequent_itemsets)

c:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(


The frequent itemsets in new dataframe are
       support        itemsets
0     0.099891        (85123A)
1     0.020848        (84029G)
2     0.019579        (84029E)
3     0.017223         (22752)
4     0.015092         (71053)
...        ...             ...
1562  0.010424  (23296, 23295)
1563  0.011467  (23294, 23293)
1564  0.010651  (23294, 23295)
1565  0.010696  (23356, 23355)
1566  0.012192  (23355, 22112)

[1567 rows x 2 columns]


In [197]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.85)
print("The rules obtained are:")
print(rules)

The rules obtained are:
              antecedents consequents  antecedent support  consequent support  \
0          (22356, 20723)     (20724)            0.017177            0.046864   
1   (22356, 22355, 20723)     (20724)            0.012282            0.046864   
2   (22356, 20723, 20719)     (20724)            0.011920            0.046864   
3   (22355, 20723, 20719)     (20724)            0.013733            0.046864   
4   (22411, 22386, 21931)    (85099B)            0.014005            0.094815   
5          (21080, 21086)     (21094)            0.013416            0.023885   
6                 (22916)     (22917)            0.010741            0.010877   
7                 (22917)     (22916)            0.010877            0.010741   
8   (22355, 20719, 22356)     (20724)            0.013234            0.046864   
9         (85099B, 21935)       (DOT)            0.012781            0.032134   
10         (22577, 22579)     (22578)            0.011285            0.023251   
11  